/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotocicletasIndexRouteImport } from './routes/motocicletas/index'
import { Route as MotocicletasMotorcycleIdRouteImport } from './routes/motocicletas/$motorcycleId'
import { Route as MotocicletasNovaRouteImport } from './routes/motocicletas/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotocicletasIndexRoute = MotocicletasIndexRouteImport.update({
  id: '/motocicletas/',
  path: '/motocicletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotocicletasMotorcycleIdRoute =
  MotocicletasMotorcycleIdRouteImport.update({
    id: '/motocicletas/$motorcycleId',
    path: '/motocicletas/$motorcycleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MotocicletasNovaRoute = MotocicletasNovaRouteImport.update({
  id: '/motocicletas/nova',
  path: '/motocicletas/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motocicletas/$motorcycleId': typeof MotocicletasMotorcycleIdRoute
  '/motocicletas/nova': typeof MotocicletasNovaRoute
  '/motocicletas/': typeof MotocicletasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motocicletas/$motorcycleId': typeof MotocicletasMotorcycleIdRoute
  '/motocicletas/nova': typeof MotocicletasNovaRoute
  '/motocicletas': typeof MotocicletasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/motocicletas/$motorcycleId': typeof MotocicletasMotorcycleIdRoute
  '/motocicletas/nova': typeof MotocicletasNovaRoute
  '/motocicletas/': typeof MotocicletasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/motocicletas/$motorcycleId'
    | '/motocicletas/nova'
    | '/motocicletas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/motocicletas/$motorcycleId' | '/motocicletas/nova' | '/motocicletas'
  id:
    | '__root__'
    | '/'
    | '/motocicletas/$motorcycleId'
    | '/motocicletas/nova'
    | '/motocicletas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotocicletasMotorcycleIdRoute: typeof MotocicletasMotorcycleIdRoute
  MotocicletasNovaRoute: typeof MotocicletasNovaRoute
  MotocicletasIndexRoute: typeof MotocicletasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motocicletas/': {
      id: '/motocicletas/'
      path: '/motocicletas'
      fullPath: '/motocicletas/'
      preLoaderRoute: typeof MotocicletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motocicletas/$motorcycleId': {
      id: '/motocicletas/$motorcycleId'
      path: '/motocicletas/$motorcycleId'
      fullPath: '/motocicletas/$motorcycleId'
      preLoaderRoute: typeof MotocicletasMotorcycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motocicletas/nova': {
      id: '/motocicletas/nova'
      path: '/motocicletas/nova'
      fullPath: '/motocicletas/nova'
      preLoaderRoute: typeof MotocicletasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotocicletasMotorcycleIdRoute: MotocicletasMotorcycleIdRoute,
  MotocicletasNovaRoute: MotocicletasNovaRoute,
  MotocicletasIndexRoute: MotocicletasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
