/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesNovoRouteImport } from './routes/clientes/novo'
import { Route as MotocicletasIndexRouteImport } from './routes/motocicletas/index'
import { Route as MotocicletasNovaRouteImport } from './routes/motocicletas/nova'
import { Route as MotocicletasRegistrarChegadaRouteImport } from './routes/motocicletas/registrar-chegada'
import { Route as PedidosIndexRouteImport } from './routes/pedidos/index'
import { Route as PedidosNovoRouteImport } from './routes/pedidos/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const MotocicletasIndexRoute = MotocicletasIndexRouteImport.update({
  id: '/motocicletas/',
  path: '/motocicletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotocicletasNovaRoute = MotocicletasNovaRouteImport.update({
  id: '/motocicletas/nova',
  path: '/motocicletas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const MotocicletasRegistrarChegadaRoute =
  MotocicletasRegistrarChegadaRouteImport.update({
    id: '/motocicletas/registrar-chegada',
    path: '/motocicletas/registrar-chegada',
    getParentRoute: () => rootRouteImport,
  } as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosNovoRoute = PedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/motocicletas/nova': typeof MotocicletasNovaRoute
  '/motocicletas/registrar-chegada': typeof MotocicletasRegistrarChegadaRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/motocicletas/': typeof MotocicletasIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/motocicletas/nova': typeof MotocicletasNovaRoute
  '/motocicletas/registrar-chegada': typeof MotocicletasRegistrarChegadaRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/motocicletas': typeof MotocicletasIndexRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/motocicletas/nova': typeof MotocicletasNovaRoute
  '/motocicletas/registrar-chegada': typeof MotocicletasRegistrarChegadaRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/motocicletas/': typeof MotocicletasIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/clientes/novo'
    | '/motocicletas/nova'
    | '/motocicletas/registrar-chegada'
    | '/pedidos/novo'
    | '/clientes/'
    | '/motocicletas/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/dashboard'
    | '/clientes/novo'
    | '/motocicletas/nova'
    | '/motocicletas/registrar-chegada'
    | '/pedidos/novo'
    | '/clientes'
    | '/motocicletas'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/dashboard'
    | '/clientes/novo'
    | '/motocicletas/nova'
    | '/motocicletas/registrar-chegada'
    | '/pedidos/novo'
    | '/clientes/'
    | '/motocicletas/'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
  MotocicletasNovaRoute: typeof MotocicletasNovaRoute
  MotocicletasRegistrarChegadaRoute: typeof MotocicletasRegistrarChegadaRoute
  PedidosNovoRoute: typeof PedidosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  MotocicletasIndexRoute: typeof MotocicletasIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motocicletas/': {
      id: '/motocicletas/'
      path: '/motocicletas'
      fullPath: '/motocicletas/'
      preLoaderRoute: typeof MotocicletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motocicletas/nova': {
      id: '/motocicletas/nova'
      path: '/motocicletas/nova'
      fullPath: '/motocicletas/nova'
      preLoaderRoute: typeof MotocicletasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motocicletas/registrar-chegada': {
      id: '/motocicletas/registrar-chegada'
      path: '/motocicletas/registrar-chegada'
      fullPath: '/motocicletas/registrar-chegada'
      preLoaderRoute: typeof MotocicletasRegistrarChegadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/novo': {
      id: '/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof PedidosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRoute,
  ClientesNovoRoute: ClientesNovoRoute,
  MotocicletasNovaRoute: MotocicletasNovaRoute,
  MotocicletasRegistrarChegadaRoute: MotocicletasRegistrarChegadaRoute,
  PedidosNovoRoute: PedidosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  MotocicletasIndexRoute: MotocicletasIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
